### ISSUE TITLE
[TRACKER] Migrate JavaScript files to TypeScript

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#10004]
This issue tracks Superset's migration from JavaScript to TypeScript (as started in [SIP-36](https://github.com/apache/incubator-superset/issues/9101)). If you'd like to help with the migration, feel free to take an unchecked directory and convert the files within the immediate directory from JavaScript/JSX to TypeScript/TSX. #9162 and #9180 provide some tips for performing the migration. Once completed and PR'ed out, feel free to tag myself (@etr2460) or anyone else in the file's git-blame for review.

We really appreciate any work done here, and are happy to help resolve any issues you may come across!

## Tracker

- [x] `src`
  - [ ] `src/CRUD`
  - [ ] `src/SqlLab`
    - [ ] `src/SqlLab/actions`
    - [ ] `src/SqlLab/components`
    - [ ] `src/SqlLab/reducers`
    - [ ] `src/SqlLab/utils`
  - [ ] `src/addSlice`
  - [ ] `src/chart`
  - [ ] `src/components`
    - [x] `src/components/ErrorMessage`
    - [ ] `src/components/FilterableTable`
    - [x] `src/components/ListView`
    - [ ] `src/components/Menu`
    - [ ] `src/components/Select`
      - [x] `src/components/Select/WindowedSelect`
  - [ ] `src/dashboard`
    - [ ] `src/dashboard/actions`
    - [ ] `src/dashboard/components`
      - [ ] `src/dashboard/components/dnd`
      - [ ] `src/dashboard/components/filterscope`
      - [ ] `src/dashboard/components/gridComponents`
        - [ ] `src/dashboard/components/gridComponents/new`
      - [ ] `src/dashboard/components/menu`
      - [ ] `src/dashboard/components/resizable`
    - [ ] `src/dashboard/containers`
    - [ ] `src/dashboard/fixtures`
    - [ ] `src/dashboard/reducers`
    - [ ] `src/dashboard/util`
      - [ ] `src/dashboard/util/charts`
      - [ ] `src/dashboard/util/logging`
  - [ ] `src/datasource`
  - [ ] `src/explore`
    - [ ] `src/explore/actions`
    - [ ] `src/explore/components`
      - [ ] `src/explore/components/controls`
    - [ ] `src/explore/controlPanels`
    - [ ] `src/explore/propTypes`
    - [ ] `src/explore/reducers`
  - [ ] `src/logger`
    - [ ] `src/logger/actions`
  - [ ] `src/messageToasts`
    - [ ] `src/messageToasts/actions`
    - [ ] `src/messageToasts/components`
    - [ ] `src/messageToasts/containers`
    - [x] `src/messageToasts/enhancers`
    - [ ] `src/messageToasts/reducers`
    - [ ] `src/messageToasts/utils`
  - [ ] `src/middleware`
  - [ ] `src/modules`
  - [ ] `src/profile`
    - [ ] `src/profile/components`
  - [ ] `src/setup`
  - [ ] `src/showSavedQuery`
  - [x] `src/types`
  - [ ] `src/utils`
    - [x] `src/views/chartList`
    - [x] `src/views/dashboardList`
    - [x] `src/views/datasetList`
  - [ ] `src/visualizations`
    - [ ] `src/visualizations/FilterBox`
    - [ ] `src/visualizations/TimeTable`
    - [ ] `src/visualizations/presets`
  - [ ] `src/welcome`
  - [ ] `spec/__mocks__`
  - [ ] `spec/fixtures`
  - [ ] `spec/helpers`
    - [ ] `spec/javascripts/CRUD`
    - [ ] `spec/javascripts/addSlice`
    - [ ] `spec/javascripts/chart`
    - [ ] `spec/javascripts/components`
      - [x] `spec/javascripts/components/ErrorMessage`
      - [ ] `spec/javascripts/components/FilterableTable`
      - [ ] `spec/javascripts/components/ListView`
      - [ ] `spec/javascripts/dashboard/actions`
      - [ ] `spec/javascripts/dashboard/components`
        - [ ] `spec/javascripts/dashboard/components/dnd`
        - [ ] `spec/javascripts/dashboard/components/gridComponents`
          - [ ] `spec/javascripts/dashboard/components/gridComponents/new`
        - [ ] `spec/javascripts/dashboard/components/menu`
        - [ ] `spec/javascripts/dashboard/components/resizable`
      - [ ] `spec/javascripts/dashboard/fixtures`
      - [ ] `spec/javascripts/dashboard/helpers`
      - [ ] `spec/javascripts/dashboard/reducers`
      - [ ] `spec/javascripts/dashboard/util`
    - [ ] `spec/javascripts/datasource`
    - [ ] `spec/javascripts/explore`
      - [ ] `spec/javascripts/explore/components`
    - [ ] `spec/javascripts/messageToasts`
      - [ ] `spec/javascripts/messageToasts/components`
      - [ ] `spec/javascripts/messageToasts/reducers`
      - [ ] `spec/javascripts/messageToasts/utils`
    - [ ] `spec/javascripts/middleware`
    - [ ] `spec/javascripts/modules`
    - [ ] `spec/javascripts/profile`
    - [ ] `spec/javascripts/showSavedQuery`
    - [ ] `spec/javascripts/sqllab`
      - [ ] `spec/javascripts/sqllab/actions`
      - [ ] `spec/javascripts/sqllab/reducers`
      - [ ] `spec/javascripts/sqllab/utils`
    - [ ] `spec/javascripts/utils`
      - [ ] `spec/javascripts/views/chartList`
      - [ ] `spec/javascripts/views/dashboardList`
      - [ ] `spec/javascripts/views/datasetList`
    - [ ] `spec/javascripts/welcome`

**Comment by tanmaylaud** [comment]
@etr2460 I noticed issues in src/components/ListView/Filters.tsx (introduced by tsx migration) in PaginatedSelectComponent. Can you please confirm if it requires a fix?

**Comment by tanmaylaud** [comment]
@etr2460 I propose adding more requirement here: Changing the class components to functional components and using react hooks.

**Comment by etr2460** [comment]
> I noticed issues in src/components/ListView/Filters.tsx (introduced by tsx migration) in PaginatedSelectComponent.

@nytai is this related to the issues you were seeing? If so, were you still planning on addressing it?

> I propose adding one more requirement here: Changing the class components to functional components and using react hooks.

In general, I agree. However we have some class components that are extremely complex and difficult to migrate to functional components. Additionally, some of our class components might simply be better off remaining as classes because of their complexity. I'd like to scope this to only requiring TypeScript migration, but with the option of also moving towards functional components with hooks. At the very least, migrating to TypeScript will make it safer and easier to go from class based to functional react components in the future, and we can do that in future work

**Comment by tanmaylaud** [comment]
> > I noticed issues in src/components/ListView/Filters.tsx (introduced by tsx migration) in PaginatedSelectComponent.
> 
> @nytai is this related to the issues you were seeing? If so, were you still planning on addressing it?
> 
> > I propose adding one more requirement here: Changing the class components to functional components and using react hooks.
> 
> In general, I agree. However we have some class components that are extremely complex and difficult to migrate to functional components. Additionally, some of our class components might simply be better off remaining as classes because of their complexity. I'd like to scope this to only requiring TypeScript migration, but with the option of also moving towards functional components with hooks. At the very least, migrating to TypeScript will make it safer and easier to go from class based to functional react components in the future, and we can do that in future work

@etr2460 Agreed! Let's encourage people to go for functional components with hooks. Beginners will also get to learn something new in the process 👍

**Comment by bera5186** [comment]
@etr2460 I would also like to work on this issue !! Can you guide me on where to start !!!

**Comment by etr2460** [comment]
Hi @bera5186! Sorry I didn't see this earlier. If you're still interested in helping out, all you need to do is find a file in the superset-frontend repo that's still in javascript and convert it to typescript. Some of the PRs linked in the issue description might help you get started

**Comment by john-bodley** [comment]
- @etr2460 to check whether there is a `pre-commit` hook to prevent new `*.js` and `*.jsx` filles.
- @etr2460 add instructions to the task regarding how to update the process tracker.

**Comment by lyndsiWilliams** [comment]
Hello! These files are currently in progress of conversion, with links to the PRs. I will update when they are complete:
- [src/SqlLab/components/SqlEditorLeftBar](https://github.com/apache/superset/pull/17926)
- [src/SqlLab/components/QueryTable](https://github.com/apache/superset/pull/17944)
