### ISSUE TITLE
P0. SQL Lab UI / UX improvements

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#1419]
- [ ] Less icons, more textual descriptions to simplify localization
- [ ] highlight next steps in the workflow, dehighlight other buttons
- [ ] provide ability to resize query and results windows
- [ ] implement split view to work with multiple tabs

**Comment by dmigo** [comment]
[This issue](https://github.com/apache/incubator-superset/issues/2237) seems to be related.
