### ISSUE TITLE
Polish Hive query execution in SQL Lab

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#2016]

**Comment by bkyryliuk** [comment]
Added hive to the staging, connection string looks like: 
`hive://hive-server2-silver.synapse:3623/default?auth=NOSASL`

Couple existing issues:

- [ ] progress tracker doesn't work

- [ ] fetching metadata fails for some tables

- [ ] no partition predicate error for table preview: http://stackoverflow.com/questions/39049620/no-partition-predicate-found-for-alias-even-when-the-partition-predicate-in-pres

- [ ]

**Comment by mime-frame** [comment]
hey @bkyryliuk, any updates on this? This will allow us to revoke SSH access from engineers that simply SSH to run Hive queries on DI servers.

**Comment by mistercrunch** [comment]
@bkyryliuk left on a long trip to southeast Asia and is joining a company named Open Door, I'll be taking over this.

**Comment by liweiwei71** [comment]
I also meet this problem. When executing a hive query, the progress can't be get, but preview a hive table is ok.

**Comment by mistercrunch** [comment]
@liweiwei71 this is a stale issue, closing. Also unclear which problem you are referring to. Please open a new issue.
