### ISSUE TITLE
Superset release roadmap

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-superset#6778]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
N/A

### Expected results
N/A

### Actual results
N/A

### Steps to reproduce
N/A

Do we have a roadmap for Superset releases?

**Comment by kristw** [comment]
Please see #6785
