### ISSUE TITLE
SQL Lab Pro Features - A rich SQL editor as part of Caravel

### ISSUE THREAD

**Issue by jefffeng** [apache/incubator-superset#866]
### Pro Features [General Availability]
- [ ] Support for Smart Defaults (defaults to basic user, but remembers preferences for pro users) - Alanna
- [ ] Support for multiple workspaces - Max
- [ ] Ability to share queries - Bogdan
- [ ] Query templating - Max

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 632 days. Feel free to comment and request for this issue to be reopened.
